import { eq, sql } from 'drizzle-orm';

import { species, speciesDataset } from '../db/schema';
import type { Db } from '../db/types';

export type Species = typeof species.$inferSelect;

/** Shape of the bundled assets/species.json, generated by scripts/species/build.ts. */
export type SpeciesDataset = { version: number; species: Species[] };

const SEEDED_ROW_ID = 1;

/** Species sorted by colloquial name, the name the picker shows. */
export function listSpecies(db: Db): Species[] {
  return db
    .select()
    .from(species)
    .orderBy(sql`${species.colloquialName} COLLATE NOCASE`)
    .all();
}

/** Version of the dataset the catalog was seeded from; 0 before the first seed. */
export function getSpeciesDatasetVersion(db: Db): number {
  const row = db
    .select({ version: speciesDataset.version })
    .from(speciesDataset)
    .where(eq(speciesDataset.id, SEEDED_ROW_ID))
    .get();
  return row?.version ?? 0;
}

/**
 * Seeds the read-only Species catalog on first launch and reseeds it whenever the bundled dataset
 * version exceeds the seeded one (ADR-0001). The catalog is replaced wholesale; user data is not
 * touched, and plants keep pointing at the same append-only Species IDs. Returns whether it ran.
 */
export function seedSpecies(db: Db, dataset: SpeciesDataset): boolean {
  if (dataset.version <= getSpeciesDatasetVersion(db)) return false;
  db.transaction((tx) => {
    tx.delete(species).run();
    // ponytail: one INSERT; SQLite takes 32766 bound values (~4000 species), chunk if the catalog ever grows past that.
    tx.insert(species).values(dataset.species).run();
    tx.insert(speciesDataset)
      .values({ id: SEEDED_ROW_ID, version: dataset.version })
      .onConflictDoUpdate({ target: speciesDataset.id, set: { version: dataset.version } })
      .run();
  });
  return true;
}
