import { eq, sql } from 'drizzle-orm';

import { species, speciesDataset } from '../db/schema';
import type { Db } from '../db/types';

export type Species = typeof species.$inferSelect;

/** Shape of the bundled assets/species.json, generated by scripts/species/build.ts. */
export type SpeciesDataset = { version: number; species: Species[] };

const SEEDED_ROW_ID = 1;

/** Species sorted by colloquial name, the name the picker shows. */
export function listSpecies(db: Db): Species[] {
  return db
    .select()
    .from(species)
    .orderBy(sql`${species.colloquialName} COLLATE NOCASE`)
    .all();
}

/**
 * The Species whose names match a search, best first: colloquial names starting with it, then
 * those with a word starting with it, then scientific names with a word starting with it, then
 * names containing it anywhere. Within each, shorter names come first.
 */
export function searchSpecies(db: Db, query: string): Species[] {
  const needle = fold(query);
  if (!needle) return [];
  const rank = (s: Species) => {
    const colloquial = fold(s.colloquialName);
    const scientific = fold(s.scientificName);
    if (colloquial.startsWith(needle)) return 0;
    if (colloquial.includes(` ${needle}`)) return 1;
    if (` ${scientific}`.includes(` ${needle}`)) return 2;
    if (colloquial.includes(needle) || scientific.includes(needle)) return 3;
    return null;
  };
  return listSpecies(db)
    .map((s) => ({ s, rank: rank(s) }))
    .filter((match): match is { s: Species; rank: number } => match.rank !== null)
    .sort((a, b) => a.rank - b.rank || a.s.colloquialName.length - b.s.colloquialName.length)
    .map(({ s }) => s);
}

/**
 * A name or a search as searchSpecies compares them: in lower case, without apostrophes (straight
 * or iOS's curly one), and hyphens and × (hybrids' sign) parting words as spaces do.
 */
function fold(name: string): string {
  return name
    .toLowerCase()
    .replace(/['’]/g, '')
    .replace(/[\s×-]+/g, ' ')
    .trim();
}

/** A catalog Species by ID; null for one the catalog doesn't know (an imported plant's, ADR-0002). */
export function getSpecies(db: Db, id: string): Species | null {
  return db.select().from(species).where(eq(species.id, id)).get() ?? null;
}

/** Version of the dataset the catalog was seeded from; 0 before the first seed. */
export function getSpeciesDatasetVersion(db: Db): number {
  const row = db
    .select({ version: speciesDataset.version })
    .from(speciesDataset)
    .where(eq(speciesDataset.id, SEEDED_ROW_ID))
    .get();
  return row?.version ?? 0;
}

/**
 * Seeds the read-only Species catalog on first launch and reseeds it whenever the bundled dataset
 * version exceeds the seeded one (ADR-0001). The catalog is replaced wholesale; user data is not
 * touched, and plants keep pointing at the same append-only Species IDs. Returns whether it ran.
 */
export function seedSpecies(db: Db, dataset: SpeciesDataset): boolean {
  if (dataset.version <= getSpeciesDatasetVersion(db)) return false;
  db.transaction((tx) => {
    tx.delete(species).run();
    // ponytail: one INSERT; SQLite takes 32766 bound values (~3600 species of 9 columns), chunk if the catalog ever grows past that.
    tx.insert(species).values(dataset.species).run();
    tx.insert(speciesDataset)
      .values({ id: SEEDED_ROW_ID, version: dataset.version })
      .onConflictDoUpdate({ target: speciesDataset.id, set: { version: dataset.version } })
      .run();
  });
  return true;
}
